## Example 6.1 in Chapra book - 'Surface Water-Quality Modeling'

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
# Parameters of lakes
volume = np.array([2e6, 4e6, 3e6])  # m^3
depth = np.array([3, 7, 3])  # m
area = np.array([0.667e6, 0.571e6, 1e6]) # m^2
loading = np.array([2000, 4000, 1000])   # kg/yr

In [3]:
Q = 1e6 # flow rate, m^3/yr
alpha = 0.5 # fraction of flow that feedback from the third lake to the first lake
v = 10 # settling rate of pollutant, m/yr

### Determine the concentration in three lakes

In [15]:
# set up interaction matrix, A

A = np.array([[Q+alpha*Q+v*area[0],          0,               alpha*Q], \
             [-(Q+alpha*Q),          Q+alpha*Q+v*area[1],        0], \
             [    0,                   -(Q+alpha*Q),        Q+alpha*Q+v*area[2]]])
W = loading

# solve matrix C by multiplying inverse matrix of A and the loading matrix W
c = np.dot((np.linalg.inv(A)), W)
print('concentration in three lakes are ', c, 'kg/m^3')

concentration in three lakes are  [0.00023466 0.0006036  0.00016569] kg/m^3


### How much concentration of the third lake is due to the reactor of the second lake?

In [16]:
B = np.linalg.inv(A)
print(B)

[[ 1.22196087e-07 -1.10531346e-09 -5.31287334e-09]
 [ 2.54222095e-08  1.38466301e-07 -1.10531346e-09]
 [ 3.31594037e-09  1.80608219e-08  8.68123504e-08]]


In [18]:
print('c_3 due to the second lake is', B[2,1]*W[1],  'kg/m^3')

c_3 due to the second lake is 7.224328744980679e-05 kg/m^3


## The case with no feedback, $\alpha=0$

In [21]:
alpha = 0.

# Recalculate Matrix A
A = np.array([[Q+alpha*Q+v*area[0],          0,               alpha*Q], \
             [-(Q+alpha*Q),          Q+alpha*Q+v*area[1],        0], \
             [    0,                   -(Q+alpha*Q),        Q+alpha*Q+v*area[2]]])

B = np.linalg.inv(A)

# Let's examine the inverse matrix. You can see that the superdiagonal terms are zeros 
print(B)

[[1.30378096e-07 0.00000000e+00 0.00000000e+00]
 [1.94304168e-08 1.49031297e-07 0.00000000e+00]
 [1.76640152e-09 1.35482997e-08 9.09090909e-08]]


In [22]:
c = np.dot(B, W)
print('concentration in three lakes are ', c, 'kg/m^3 without feedback')

concentration in three lakes are  [0.00026076 0.00063499 0.00014864] kg/m^3 without feedback
